openapi: 3.0.1
info:
  description: "Parameters for cursor based pagination. More details: https://escmconfluence.1dc.com/display/EGA/Pagination"
  version: 1.0
  title: "Parameters for cursor based pagination"
components:
  #########################
  # Cursor based Pagination headers
  #########################
  parameters:
    LimitParam:
      in: query
      name: limit
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 100
        default: 20
      description: "The number of items to return"
    PageAfterParam:
      in: query
      name: pageAfter
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 100
        default: 20
      description: "The number of items to return"
    PageBeforeParam:
      in: query
      name: pageBefore
      schema:
        type: integer
        format: int32
        minimum: 2
        maximum: 100
        default: 20
      description: "The number of items to return"