openapi: 3.0.1
info:
  title: Common Schema elements
  description: "Contains common schema elements"
  version: 'v1'

components:
  schemas:
    Date:
      title: "Date"
      required:
      - date
      type: string
      description: "Common date object in YYYY-MM-DD format as per RFC 3339, section 5.6."
      format: date
      example: "2019-06-30"
    Datetime:
      title: "Datetime"
      required:
      - dateTime
      type: string
      format: date-time
      description: "Common datetime object in  as per RFC 3339, section 5.6."
      example: "2019-03-20T09:12:28+01:00"

    MerchantNumber:
      title: "merchantNumber"
      type: string
      description: "External merchant id; from source system"
      minLength: 0
      maxLength: 20
      example: "MERCHANT_349021"
      pattern: '^[a-zA-Z0-9_]{0,20}$'
